import Head from 'next/head'
import Link from 'next/link'
import { FaPlus } from 'react-icons/fa'
import Stories from '../components/feed/Stories'
import { stories } from '../utils/Stories'

export default function Home() {
  return (
    <>
      <Head>
        <title>Storybook Feed</title>
        <meta name='description' content='Generated by Storybook Feed' />
      </Head>

      <main>
        <Stories stories={stories} />
      </main>

      <Link href='/profile/stories'>
        <a>
          <button
            className='btn btn-success btn-sm rounded-pill position-fixed shadow-lg animate__bounceIn animate__lightSpeedInRight'
            style={{ zIndex: 111, right: '30px', bottom: '30px' }}
          >
            <FaPlus className='mb-1' />
          </button>
        </a>
      </Link>
    </>
  )
}
