import Head from 'next/head'
import { FaPlus } from 'react-icons/fa'
import ComponentStories from '../components/feed/Stories'
import { getPublicStories } from '../api/stories'
import { useQuery } from 'react-query'
import db from '../utils/db'
import Stories from '../models/Stories'
import convertDocToObj from '../utils/convertDocToObj'

export default function Home({ stories }) {
  const { data } = useQuery('stories', () => getPublicStories(), {
    initialData: stories,
    retry: 0,
    enabled: !!stories,
  })

  return (
    <>
      <Head>
        <title>Storybook Feed</title>
        <meta name='description' content='Generated by Storybook Feed' />
      </Head>

      <main>
        <ComponentStories stories={data && data} />
      </main>
      {/* eslint-disable */}
      <a href='/profile/stories'>
        <button
          className='btn btn-success btn-sm rounded-pill position-fixed shadow-lg animate__bounceIn animate__lightSpeedInRight'
          style={{ zIndex: 111, right: '30px', bottom: '30px' }}
        >
          <FaPlus className='mb-1' />
        </button>
      </a>
      {/* eslint-enable */}
    </>
  )
}

export async function getServerSideProps() {
  await db()
  const stories = await Stories.find({ type: 'public' }).lean()
  return { props: { stories: stories.map(convertDocToObj) } }
}
