import Head from 'next/head'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Storybook Feed</title>
        <meta name='description' content='Generated by Storybook Feed' />
      </Head>

      <main>
        <h1 className='text-center text-primary fw-light'>Storybook Feed</h1>
      </main>
    </div>
  )
}
